### ISSUE TITLE
Bot doesnt say anything

### ISSUE THREAD

**Issue by PRoton208** [Carbowix/Cleve#10]
I dont know why the bot starts typing and then it stopped doesnt send any message
[message[](![error1](https://user-images.githubusercontent.com/84762676/129676431-562d7d29-aa7a-4da4-9b14-462f135118d7.JPG))](url
![error2](https://user-images.githubusercontent.com/84762676/129676446-6738aa69-3208-494b-85b9-fe0219c1531e.JPG)
)

**Comment by Carbowix** [comment]
Hello,
Please make sure you followed the instructions carefully and added every API detail that's needed. The bot works totally fine. If there are any errors in the console, feel free to show it here for further assistance.

**Comment by TheVirus-Limiter** [comment]
![unknown](https://user-images.githubusercontent.com/64677380/130069715-438d4d0e-9953-40d8-8784-f8129a1374ee.png)

**Comment by Carbowix** [comment]
> ![unknown](https://user-images.githubusercontent.com/64677380/130069715-438d4d0e-9953-40d8-8784-f8129a1374ee.png)
> 

It seems that brainshop.ai API is down. So wait till it online again. Nothing I can do from my side.

**Comment by TheVirus-Limiter** [comment]
ok tysm

**Comment by Dhaloi** [comment]
That bug fixed this day and works perfectly!

**Comment by Dhaloi** [comment]
brainshop.ai API was down its not a bug.

**Comment by Carbowix** [comment]
> That bug fixed this day and works perfectly!
> 

thank you for the update. I just kept the issue opened to keep newcomers aware of  API downtime.
