### ISSUE TITLE
Client_Missing Intents

### ISSUE THREAD

**Issue by PRoton208** [Carbowix/Cleve#11]
Bascially the bot works replied BUT when i use for like 20 min the goes ofline code in the terminal stop running but when i try to run the command again this appear I install yarn discord.js node.js/npm I copy past your code but it still gives me the same issue what shall i do??
![image](https://user-images.githubusercontent.com/84762676/129851694-ebffa214-bfd7-45d5-8e8c-e34a64a98771.png)

**Comment by Carbowix** [comment]
I'm aware of the issue and I'll be working to patch it by today. Thank you for the report

**Comment by PRoton208** [comment]
> I'm aware of the issue and I'll be working to patch it by today. Thank you for the report

Thank you

**Comment by Carbowix** [comment]
> > I'm aware of the issue and I'll be working to patch it by today. Thank you for the report
> 
> Thank you, tell me when you're done

Updated the bot to the newest discord.js version. I suggest re-cloning the repo. to a new empty folder and follow the new [README](https://github.com/Carbowix/Cleve#readme) instructions carefully.
