### ISSUE TITLE
question

### ISSUE THREAD

**Issue by LolekLiam** [Carbowix/Cleve#19]
how can i edit the code so that you dont have to ping the bot? so it will always listen to a specific channel without pinging the bot.
pls show me how to do that @Carbowix

**Comment by Carbowix** [comment]
remove [line 32](https://github.com/Carbowix/Cleve/blob/master/index.js#L32) in `index.js` and it'll respond without ping. For talking in a specific channel, edit `"channel"` with your channel id in `misc/config.json`.
