### ISSUE TITLE
Bot not answering

### ISSUE THREAD

**Issue by InfoBlock** [Carbowix/Cleve#21]
My code looks exactly like the given source code but the Bot doesnt reply to questions even though its online, Console showing no errors or anything either

[Bot not replying](https://infoblock.gq/media/5v89l.png)
[Bot Online on Discord](https://infoblock.gq/media/ojqvy.png)
[Console](https://infoblock.gq/media/faugt.png)

**Comment by Carbowix** [comment]
The bot works fine, make sure you follow the instructions written carefully in [README.md](https://github.com/Carbowix/Cleve/blob/master/README.md) and everything should be fine.
