### ISSUE TITLE
Strange timeout Error 

### ISSUE THREAD

**Issue by mrtylergamer** [Carbowix/Cleve#28]
Keep getting this error whenever trying to communicate with the api doesnt appear to be code related but unsure

`FetchError: invalid json response body at http://api.brainshop.ai/get?bid=<Hidden brain id>&key=<Hidden api key>&uid=<hidden>&msg=are+you+able+to+respond reason: Unexpected token ( in JSON at position 0`

Loaded the link on Firefox showed a timeout error 

Is this my internet or is it api side

**Comment by Carbowix** [comment]
Yes, it is the API side.
