### ISSUE TITLE
Hello, I cant seem to get it to work. Heres my config, i have aldready installed NPM, and added the blackbird stuff.

### ISSUE THREAD

**Issue by Voidrunner42** [Carbowix/Cleve#30]
Any help will be appreciated.

Here is my config:

{
    "bot_token": "xxxx",
    "status": {
        "state": "online",
        "type": "Playing",
        "name": "Chat with me!"
    },
    "chat": {
        "url": "http://api.brainshop.ai/get",
        "brainID": "xxxxxx",
        "key": "xxxxxxxxxxx",
        "channel": ""
    }
}

**Comment by Carbowix** [comment]
Need more details. Show any errors that appear on your console. If you are unable to start the bot, please read the whole `README.md` carefully.
