### ISSUE TITLE
are you ok?

### ISSUE THREAD

**Issue by jhuiry8** [Carbowix/Cleve#31]
/home/runner/test/node_modules/discord.js/src/rest/RESTManager.js:32
    const token = this.client.token ?? this.client.accessToken;
                                     ^

SyntaxError: Unexpected token '?'
Hint: hit control+c anytime to enter REPL.


**Comment by Carbowix** [comment]
https://stackoverflow.com/questions/69355690/const-token-this-client-token-this-client-accesstoken-syntaxerror-unexpec
