### ISSUE TITLE
unable to start bot please help

### ISSUE THREAD

**Issue by SpidyKhrish007** [Carbowix/Cleve#38]
![Untitled](https://user-images.githubusercontent.com/106378292/170673239-db67ca10-49e8-410a-a364-c99e84549f89.png)

**Comment by Carbowix** [comment]
Hello there,

to start the bot you need to write `node index.js`. if it still doesn't work then please follow the installation [instructions](https://www.github.com/Carbowix/Cleve/tree/master/README.md)

**Comment by SpidyKhrish007** [comment]
> Hello there,
> 
> to start the bot you need to write `node index.js`. if it still doesn't work then please follow the installation [instructions](https://www.github.com/Carbowix/Cleve/tree/master/README.md)

its on repl.it and i followed all the instructions

**Comment by Carbowix** [comment]
> > Hello there,
> > to start the bot you need to write `node index.js`. if it still doesn't work then please follow the installation [instructions](https://www.github.com/Carbowix/Cleve/tree/master/README.md)
> 
> i still got same thing after i write the node index.js. its on repl.it and i followed all the instructions
> 
> https://replit.com/join/infihnxvxi-iamopcoder join my repel and find the error i have removed some details of token and all for soem privacy reasons

I've updated your repl.it to work normally again. All you have to do now is to insert back your private details and press **RUN**. 

Your problem is that your Node.js version was `12.0` while the least supported version is `16.x`.
