### ISSUE TITLE
Need Help Code Change

### ISSUE THREAD

**Issue by SpidyKhrish007** [Carbowix/Cleve#39]
![Untitled](https://user-images.githubusercontent.com/106378292/170854804-0e09cdea-c904-4be7-a31a-3fb8c4ea8b1b.png)

I Want The Bot To Reply Without Ping Can You Help Me With it Please

**Comment by SpidyKhrish007** [comment]
I Want The Bot To Reply Without Ping Can You Help Me With it Please

**Comment by InfoBlock** [comment]
> I Want The Bot To Reply Without Ping Can You Help Me With it Please And where can i add code to get the uptime link

Check your util.js - I haven't done anything with discord.js v13 yet but I think I can help you out

Have you done anything to "handleTalk" ?
If my assumptions are right it shouldn't ping on a reply if you keep the handleTalk default as it is
```js
const handleTalk = async (msg) => {
    msg.content = msg.content.replace(/^<@!?[0-9]{1,20}> ?/i, '');
    if (msg.content.length < 2 || (!isNaN(chat.channel) && chat.channel != msg.channel.id)) return;
    msg.channel.sendTyping();
    urlOptions.uid = msg.author.id;
    urlOptions.msg = msg.content;
    mainURL.search = new URLSearchParams(urlOptions).toString();
    try {
        let reply = await request(mainURL);
        if (reply) {
            reply = await reply.json();
            msg.reply({
                content: reply.cnt,
                allowedMentions: {
                    repliedUser: false
                }
            })
        }
    } catch (e) {
        console.log(e.stack);
    }
};
```
I believe if you switch `repliedUser: false` to `repliedUser: true` it would ping the user on reply.

**Comment by SpidyKhrish007** [comment]
> > I Want The Bot To Reply Without Ping Can You Help Me With it Please And where can i add code to get the uptime link
> 
> Check your util.js - I haven't done anything with discord.js v13 yet but I think I can help you out
> 
> Have you done anything to "handleTalk" ? If my assumptions are right it shouldn't ping on a reply if you keep the handleTalk default as it is
> 
> ```js
> const handleTalk = async (msg) => {
>     msg.content = msg.content.replace(/^<@!?[0-9]{1,20}> ?/i, '');
>     if (msg.content.length < 2 || (!isNaN(chat.channel) && chat.channel != msg.channel.id)) return;
>     msg.channel.sendTyping();
>     urlOptions.uid = msg.author.id;
>     urlOptions.msg = msg.content;
>     mainURL.search = new URLSearchParams(urlOptions).toString();
>     try {
>         let reply = await request(mainURL);
>         if (reply) {
>             reply = await reply.json();
>             msg.reply({
>                 content: reply.cnt,
>                 allowedMentions: {
>                     repliedUser: false
>                 }
>             })
>         }
>     } catch (e) {
>         console.log(e.stack);
>     }
> };
> ```
> 
> I believe if you switch `repliedUser: false` to `repliedUser: true` it would ping the user on reply.

Ok and what about uptime where should I add the uptime code in which file ?

**Comment by InfoBlock** [comment]
> > > I Want The Bot To Reply Without Ping Can You Help Me With it Please And where can i add code to get the uptime link
> > 
> > 
> > Check your util.js - I haven't done anything with discord.js v13 yet but I think I can help you out
> > Have you done anything to "handleTalk" ? If my assumptions are right it shouldn't ping on a reply if you keep the handleTalk default as it is
> > ```js
> > const handleTalk = async (msg) => {
> >     msg.content = msg.content.replace(/^<@!?[0-9]{1,20}> ?/i, '');
> >     if (msg.content.length < 2 || (!isNaN(chat.channel) && chat.channel != msg.channel.id)) return;
> >     msg.channel.sendTyping();
> >     urlOptions.uid = msg.author.id;
> >     urlOptions.msg = msg.content;
> >     mainURL.search = new URLSearchParams(urlOptions).toString();
> >     try {
> >         let reply = await request(mainURL);
> >         if (reply) {
> >             reply = await reply.json();
> >             msg.reply({
> >                 content: reply.cnt,
> >                 allowedMentions: {
> >                     repliedUser: false
> >                 }
> >             })
> >         }
> >     } catch (e) {
> >         console.log(e.stack);
> >     }
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I believe if you switch `repliedUser: false` to `repliedUser: true` it would ping the user on reply.
> 
> Ok and what about uptime where should I add the uptime code in which file ?

Uptime would be an command or await message content, you can either send the normal client.uptime() or use `moment` to set the Uptime precisely
