### ISSUE TITLE
No Such File as "details.json"

### ISSUE THREAD

**Issue by Kief5555** [Carbowix/Cleve#4]
I got this error:
<img width="528" alt="Screen Shot 2021-01-28 at 7 41 48 PM" src="https://user-images.githubusercontent.com/67562560/106228754-dd46d300-61a0-11eb-871d-3c29ae1d69ce.png">

**Comment by Carbowix** [comment]
Apologies, there was a mistake in the README.md. The file name is config.json located in the misc [folder](https://www.github.com/Carbowix/Cleve/tree/master/misc%2Fconfig.json). Your error is failing to install the required node module packages. Dont forget to run `npm install` or `yarn install` after you fill up the details in `config.json`.
If you have anymore inquiries, feel free to open a issue again.

**Comment by Kief5555** [comment]
Thanks
