### ISSUE TITLE
Channel id

### ISSUE THREAD

**Issue by Sniper-34** [Carbowix/Cleve#40]
Hey carbowix ! I just wanted a small help with the chatbot's amazing code.
I want to modify the chatbot so that it responds not in only one channel but also in an user defined channels

**Comment by Carbowix** [comment]
You need to know how to create [commands](https://discordjs.guide/creating-your-bot/creating-commands.html#command-deployment-script) then get the `channel id` from the command and save it somewhere. You can edit the following [line](https://github.com/Carbowix/Cleve/blob/master/util.js#L25) to control how the bot responds to which channels. Right now it only responds to any channel or the specified channel in `misc/config.json`. You need to have scripting knowledge to edit the bot accordingly.
