### ISSUE TITLE
bot not replying message

### ISSUE THREAD

**Issue by SyntX34** [Carbowix/Cleve#49]
reason: Unexpected token S in JSON at position 0
    at /home/runner/Chatbot/node_modules/node-fetch/lib/index.js:273:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by Carbowix** [comment]
Should be working fine. The API might have been down the moment you tried to chat with the bot.
If the issue still persists, make sure you followed the installation steps correctly in order to gain a proper result from the API.
