### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by Kief5555** [Carbowix/Cleve#5]
<img width="496" alt="Screen Shot 2021-01-30 at 11 10 26 AM" src="https://user-images.githubusercontent.com/67562560/106365647-c52f9a80-62eb-11eb-9499-daa1c9906775.png">
I got this issue when I indexed the "index.js"
<img width="842" alt="Screen Shot 2021-01-30 at 11 11 01 AM" src="https://user-images.githubusercontent.com/67562560/106365683-e7c1b380-62eb-11eb-8699-154bd07ad506.png">

**Comment by Kief5555** [comment]
How would I fix this?

**Comment by Carbowix** [comment]
As I said before your node module packages are missing.You can cann install using [npm install](https://stackoverflow.com/questions/8367031/how-do-i-install-package-json-dependencies-in-the-current-directory-using-npm). If you're unable still to get it to work, consider learning NodeJS before using this project.
