### ISSUE TITLE
Trying to run this in replit but recieving this error when running any ideas?

### ISSUE THREAD

**Issue by trrsmgl** [Carbowix/Cleve#50]
npm run start
npm ERR! Missing script: "start"

**Comment by Carbowix** [comment]
adding the following to your `package.json` file should fix the issue:
```json
{
  "scripts": {
    "start": "node index.js",
   }
}
```

**Comment by trrsmgl** [comment]
now i got a new error after adding start to line 1 of .json

`npm ERR! code EJSONPARSE
npm ERR! path /home/runner/Cleve/package.json
npm ERR! JSON.parse Unexpected token "{" (0x7B) in JSON at position 53 while parsing near "...de index.js\"\n   }\n}\n{\n  \"name\": \"cleve\",..."
npm ERR! JSON.parse Failed to parse JSON data.
npm ERR! JSON.parse Note: package.json must be actual JSON, not just JavaScript.`

**Comment by trrsmgl** [comment]
now im  have a new error after adding start to line 1

`
npm ERR! code EJSONPARSE
npm ERR! path /home/runner/Cleve/package.json
npm ERR! JSON.parse Unexpected token "{" (0x7B) in JSON at position 53 while parsing near "...de index.js\"\n   }\n}\n{\n  \"name\": \"cleve\",..."
npm ERR! JSON.parse Failed to parse JSON data.
npm ERR! JSON.parse Note: package.json must be actual JSON, not just JavaScript.
`

**Comment by Carbowix** [comment]
Must be a syntax error from your `package.json` file. Can you show it to me for further help?

**Comment by trrsmgl** [comment]
```{
  "scripts": {
    "start": "node index.js"
  }
}

{
  "name": "cleve",
  "version": "1.0.0",
  "description": "Basic open sourced Discord chat bot powered by brainshop.ai",
  "main": "index.js",
  "dependencies": {
    "busboy": "^1.6.0",
    "discord-api-types": "^0.37.29",
    "discord.js": "^14.7.1",
    "ieee754": "^1.2.1",
    "fast-deep-equal": "^3.1.3",
    "lodash": "^4.17.21",
    "inherits": "^2.0.4",
    "node-fetch": "^2.6.8",
    "prism-media": "^1.3.4",
    "readable-stream": "^3.6.0",
    "lodash.snakecase": "^4.1.1",
    "safe-buffer": "^5.2.1",
    "streamsearch": "^1.1.0",
    "string_decoder": "^1.3.0",
    "file-type": "^18.0.0",
    "tr46": "^0.0.3",
    "strtok3": "^7.0.0",
    "readable-web-to-node-stream": "^3.0.2",
    "tslib": "^2.4.1",
    "undici": "^5.14.0",
    "util-deprecate": "^1.0.2",
    "whatwg-url": "^5.0.0",
    "webidl-conversions": "^3.0.1",
    "ws": "^8.11.0",
    "peek-readable": "^5.0.0",
    "ts-mixer": "^6.0.2",
    "token-types": "^5.0.1"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  }
```

**Comment by trrsmgl** [comment]
I figured out my issue feel dumb but thanks for the help
