### ISSUE TITLE
The output is "[CLEVE] Started and ready to chat!" but the bot ain't responding!

### ISSUE THREAD

**Issue by 8awv** [Carbowix/Cleve#52]
Hello, there's problem that I'm facing right now, the bot is connected but the status isn't changing and he isn't respoding in the channel

{
    "bot_token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "status": {
        "state": "idle",
        "type": "PLAYING",
        "name": "Chat simulator"
    },
    "chat": {
        "url": "http://api.brainshop.ai/get",
        "brainID": "xxxxxx",
        "key": "*****************",
        "channel": "**********************"
    }
}

this is the config.json

**Comment by 8awv** [comment]
?

**Comment by Carbowix** [comment]
Hello there,
Please make sure your details in `misc/config.json` are all correct and check the console for any errors while attempting to message the bot.
