### ISSUE TITLE
Unexpected token 'S'

### ISSUE THREAD

**Issue by Arlis-Coder** [Carbowix/Cleve#53]
Hi there when i try send a message to bot, i got this error

[CLEVE] Started and ready to chat!
FetchError: invalid json response body at http://api.brainshop.ai/get?bid=[bid]&key=[key]&uid=[uid]&msg=hello reason: Unexpected token 'S', "SPAM, cont"... is not valid JSON
at D:\path\path\node_modules\node-fetch\lib\index.js:273:32
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Object.handleTalk (D:\path\path\util.js:33:21) 

can you help me?

**Comment by Carbowix** [comment]
Hello there,
Things should be working normally. Are you sure you followed the installation steps correctly?
