### ISSUE TITLE
Bot restarts if someone DM him

### ISSUE THREAD

**Issue by ManucrackYT** [Carbowix/Cleve#55]
![imagen](https://user-images.githubusercontent.com/71397795/229178654-de0da618-5623-42f9-945b-29c3ebecb104.png)

**Comment by Carbowix** [comment]
Apologies for the inconvenience, the issue should be fixed now. Make sure to pull the latest Cleve update.
![image](https://user-images.githubusercontent.com/24420693/229189732-3826f16d-6bf8-4d64-8e4d-e476db0a7127.png)

**Comment by ManucrackYT** [comment]
Thanks, also I can't enable NoMention, it doesn't works and you need to mention the bot

**Comment by Carbowix** [comment]
Please check the FAQ section in the [README](https://github.com/Carbowix/Cleve/blob/master/README.md) to know more about the "no mention" feature

**Comment by ManucrackYT** [comment]
No but I enabled it and still not working

**Comment by Carbowix** [comment]
As i said, make sure to read the FAQ section first. It works fine
![image](https://user-images.githubusercontent.com/24420693/229290737-688d518b-53e2-412a-a398-bcea6a60b18c.png)

Make sure you make `"noMention": true` in **src/misc/config.json** and enable **Message Content Intent** in your discord application portal. Check [this](https://autocode.com/discord/threads/what-are-discord-privileged-intents-and-how-do-i-enable-them-tutorial-0c3f9977/) to know how to enable. Also make sure to restart the bot completely once you do the changes.

**Comment by ManucrackYT** [comment]
But for make the bot works I had to put something in an event file or else, the bot when you mention him it reboots

**Comment by ManucrackYT** [comment]
![imagen](https://user-images.githubusercontent.com/71397795/229472474-716cb093-1d8d-419b-bc07-73dc084fbf92.png)
Look, I have enabled it but bot doesn't reply to the channel I selected
![imagen](https://user-images.githubusercontent.com/71397795/229472731-9c4b6d0a-641e-43a9-b3a3-231e5b95a406.png)

**Comment by ManucrackYT** [comment]
Oh nvm rn i pulled new changes and everything is working now thanks
