### ISSUE TITLE
Unable to get a responce

### ISSUE THREAD

**Issue by Pooky12332** [Carbowix/Cleve#56]
When trying to run the bot or to get to type a response, it comes up with this

`Unable to connect to API: Error: [401] Unable to process request:
Reason: Unauthorized`

I changed everything In the config file, and still nothing

**Comment by Carbowix** [comment]
Are you sure that you followed the installation steps correctly? Including the API key/brainID

**Comment by Pooky12332** [comment]
I'm pretty sure, I know I set up the Key and ID right, the url idk
Do I leave it as `http://api.brainshop.ai/get?` or do I use the one from the brain?

**Comment by Carbowix** [comment]
You should leave the **"url** as it is and insert your brainID & key relative to their respective places.

**Comment by Carbowix** [comment]
You can join my [discord](https://discord.com/invite/nntu7rgxtP) so I can help you more with the issue
