### ISSUE TITLE
Bot not responding

### ISSUE THREAD

**Issue by Discobotdevlolhehe** [Carbowix/Cleve#57]
when I run /setchannel it says application did not respond and when i run it again it says the channel is already registered. But when i send a message i dont get a respond and this is what my console shows:
[ERROR] <ref *1> Client {
  _events: [Object: null prototype] {
    shardDisconnect: [Function (anonymous)],
    disconnect: [Function: bound onceWrapper] { listener: [Function (anonymous)] },
    error: [Function (anonymous)],
    interactionCreate: [Function (anonymous)],
    messageCreate: [Function (anonymous)],
    ready: [Function (anonymous)]
  },
  _eventsCount: 6,
  _maxListeners: undefined,
  options: {
    intents: IntentsBitField { bitfield: 23041 },
    partials: [ 1, 3, 0, 2 ],
    presence: { activities: [Array], status: 'streaming', user: [Object] },
    shards: [ 0 ],
    failIfNotExists: false,
    allowedMentions: { parse: [Array], users: [], roles: [], repliedUser: false },
    closeTimeout: 5000,
    waitGuildTimeout: 15000,
    shardCount: 1,
    makeCache: [Function (anonymous)],
    sweepers: { threads: [Object] },
    ws: {
      large_threshold: 50,
      compress: false,
      properties: [Object],
      version: 10,
      presence: [Object]
    },
    rest: {
      agent: [Agent],
      api: 'https://discord.com/api',
      authPrefix: 'Bot',
      cdn: 'https://cdn.discordapp.com',
      headers: {},
      invalidRequestWarningInterval: 0,
      globalRequestsPerSecond: 50,
      offset: 50,
      rejectOnRateLimit: null,
      retries: 3,
      timeout: 15000,
      userAgentAppendix: 'discord.js/14.9.0 Node.js/v18.12.1',
      version: '10',
      hashSweepInterval: 14400000,
      hashLifetime: 86400000,
      handlerSweepInterval: 3600000
    },
    jsonTransformer: [Function: toSnakeCase]
  },
  rest: REST {
    _events: [Object: null prototype] {
      newListener: [Function (anonymous)],
      removeListener: [Function (anonymous)]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    cdn: CDN { base: 'https://cdn.discordapp.com' },
    requestManager: RequestManager {
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      agent: [Agent],
      globalRemaining: 49,
      globalDelay: null,
      globalReset: 1682779250140,
      hashes: [Collection [Map]],
      handlers: [Collection [Map]],
      hashTimer: Timeout {
        _idleTimeout: 14400000,
        _idlePrev: [TimersList],
        _idleNext: [TimersList],
        _idleStart: 1003,
        _onTimeout: [Function (anonymous)],
        _timerArgs: undefined,
        _repeat: 14400000,
        _destroyed: false,
        [Symbol(refed)]: false,
        [Symbol(kHasPrimitive)]: false,
        [Symbol(asyncId)]: 6,
        [Symbol(triggerId)]: 1
      },
      handlerTimer: Timeout {
        _idleTimeout: 3600000,
        _idlePrev: [Timeout],
        _idleNext: [TimersList],
        _idleStart: 1003,
        _onTimeout: [Function (anonymous)],
        _timerArgs: undefined,
        _repeat: 3600000,
        _destroyed: false,
        [Symbol(refed)]: false,
        [Symbol(kHasPrimitive)]: false,
        [Symbol(asyncId)]: 7,
        [Symbol(triggerId)]: 1
      },
      options: [Object],
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false
  },
  ws: WebSocketManager {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    gateway: 'wss://gateway.discord.gg/',
    totalShards: 1,
    shards: Collection(1) [Map] { 0 => [WebSocketShard] },
    status: 0,
    destroyed: false,
    reconnecting: false,
    [Symbol(kCapture)]: false
  },
  actions: ActionsManager {
    injectedUser: Symbol(djs.actions.injectedUser),
    injectedChannel: Symbol(djs.actions.injectedChannel),
    injectedMessage: Symbol(djs.actions.injectedMessage),
    client: [Circular *1],
    ApplicationCommandPermissionsUpdate: ApplicationCommandPermissionsUpdateAction { client: [Circular *1] },
    AutoModerationActionExecution: AutoModerationActionExecutionAction { client: [Circular *1] },
    AutoModerationRuleCreate: AutoModerationRuleCreateAction { client: [Circular *1] },
    AutoModerationRuleDelete: AutoModerationRuleDeleteAction { client: [Circular *1] },
    AutoModerationRuleUpdate: AutoModerationRuleUpdateAction { client: [Circular *1] },
    ChannelCreate: ChannelCreateAction { client: [Circular *1] },
    ChannelDelete: ChannelDeleteAction { client: [Circular *1] },
    ChannelUpdate: ChannelUpdateAction { client: [Circular *1] },
    GuildAuditLogEntryCreate: GuildAuditLogEntryCreateAction { client: [Circular *1] },
    GuildBanAdd: GuildBanAdd { client: [Circular *1] },
    GuildBanRemove: GuildBanRemove { client: [Circular *1] },
    GuildChannelsPositionUpdate: GuildChannelsPositionUpdate { client: [Circular *1] },
    GuildDelete: GuildDeleteAction { client: [Circular *1] },
    GuildEmojiCreate: GuildEmojiCreateAction { client: [Circular *1] },
    GuildEmojiDelete: GuildEmojiDeleteAction { client: [Circular *1] },
    GuildEmojiUpdate: GuildEmojiUpdateAction { client: [Circular *1] },
    GuildEmojisUpdate: GuildEmojisUpdateAction { client: [Circular *1] },
    GuildIntegrationsUpdate: GuildIntegrationsUpdate { client: [Circular *1] },
    GuildMemberRemove: GuildMemberRemoveAction { client: [Circular *1] },
    GuildMemberUpdate: GuildMemberUpdateAction { client: [Circular *1] },
    GuildRoleCreate: GuildRoleCreate { client: [Circular *1] },
    GuildRoleDelete: GuildRoleDeleteAction { client: [Circular *1] },
    GuildRoleUpdate: GuildRoleUpdateAction { client: [Circular *1] },
    GuildRolesPositionUpdate: GuildRolesPositionUpdate { client: [Circular *1] },
    GuildScheduledEventCreate: GuildScheduledEventCreateAction { client: [Circular *1] },
    GuildScheduledEventDelete: GuildScheduledEventDeleteAction { client: [Circular *1] },
    GuildScheduledEventUpdate: GuildScheduledEventUpdateAction { client: [Circular *1] },
    GuildScheduledEventUserAdd: GuildScheduledEventUserAddAction { client: [Circular *1] },
    GuildScheduledEventUserRemove: GuildScheduledEventUserRemoveAction { client: [Circular *1] },
    GuildStickerCreate: GuildStickerCreateAction { client: [Circular *1] },
    GuildStickerDelete: GuildStickerDeleteAction { client: [Circular *1] },
    GuildStickerUpdate: GuildStickerUpdateAction { client: [Circular *1] },
    GuildStickersUpdate: GuildStickersUpdateAction { client: [Circular *1] },
    GuildUpdate: GuildUpdateAction { client: [Circular *1] },
    InteractionCreate: InteractionCreateAction { client: [Circular *1] },
    InviteCreate: InviteCreateAction { client: [Circular *1] },
    InviteDelete: InviteDeleteAction { client: [Circular *1] },
    MessageCreate: MessageCreateAction { client: [Circular *1] },
    MessageDelete: MessageDeleteAction { client: [Circular *1] },
    MessageDeleteBulk: MessageDeleteBulkAction { client: [Circular *1] },
    MessageReactionAdd: MessageReactionAdd { client: [Circular *1] },
    MessageReactionRemove: MessageReactionRemove { client: [Circular *1] },
    MessageReactionRemoveAll: MessageReactionRemoveAll { client: [Circular *1] },
    MessageReactionRemoveEmoji: MessageReactionRemoveEmoji { client: [Circular *1] },
    MessageUpdate: MessageUpdateAction { client: [Circular *1] },
    PresenceUpdate: PresenceUpdateAction { client: [Circular *1] },
    StageInstanceCreate: StageInstanceCreateAction { client: [Circular *1] },
    StageInstanceDelete: StageInstanceDeleteAction { client: [Circular *1] },
    StageInstanceUpdate: StageInstanceUpdateAction { client: [Circular *1] },
    ThreadCreate: ThreadCreateAction { client: [Circular *1] },
    ThreadDelete: ThreadDeleteAction { client: [Circular *1] },
    ThreadListSync: ThreadListSyncAction { client: [Circular *1] },
    ThreadMemberUpdate: ThreadMemberUpdateAction { client: [Circular *1] },
    ThreadMembersUpdate: ThreadMembersUpdateAction { client: [Circular *1] },
    TypingStart: TypingStart { client: [Circular *1] },
    UserUpdate: UserUpdateAction { client: [Circular *1] },
    VoiceStateUpdate: VoiceStateUpdate { client: [Circular *1] },
    WebhooksUpdate: WebhooksUpdate { client: [Circular *1] }
  },
  voice: ClientVoiceManager { adapters: Map(0) {} },
  shard: null,
  users: UserManager {},
  guilds: GuildManager {},
  channels: ChannelManager {},
  sweepers: Sweepers {
    options: { threads: [Object] },
    intervals: {
      autoModerationRules: null,
      applicationCommands: null,
      bans: null,
      emojis: null,
      invites: null,
      guildMembers: null,
      messages: null,
      presences: null,
      reactions: null,
      stageInstances: null,
      stickers: null,
      threadMembers: null,
      threads: Timeout {
        _idleTimeout: 3600000,
        _idlePrev: [TimersList],
        _idleNext: [Timeout],
        _idleStart: 1095,
        _onTimeout: [Function (anonymous)],
        _timerArgs: undefined,
        _repeat: 3600000,
        _destroyed: false,
        [Symbol(refed)]: false,
        [Symbol(kHasPrimitive)]: false,
        [Symbol(asyncId)]: 8,
        [Symbol(triggerId)]: 1
      },
      users: null,
      voiceStates: null
    }
  },
  presence: ClientPresence {
    userId: null,
    guild: null,
    status: 'streaming',
    activities: [ [Activity] ],
    clientStatus: null
  },
  user: ClientUser {
    id: '901368106847465492',
    bot: true,
    system: false,
    flags: UserFlagsBitField { bitfield: 0 },
    username: 'BOT.AI',
    discriminator: '8844',
    avatar: 'b422596edcc8765e6987357e841e9689',
    banner: undefined,
    accentColor: undefined,
    verified: true,
    mfaEnabled: false
  },
  application: ClientApplication {
    id: '901368106847465492',
    name: null,
    description: null,
    icon: null,
    tags: [],
    installParams: null,
    customInstallURL: null,
    flags: ApplicationFlagsBitField { bitfield: 42508288 },
    cover: null,
    rpcOrigins: [],
    botRequireCodeGrant: null,
    botPublic: null,
    roleConnectionsVerificationURL: null,
    owner: null,
    commands: ApplicationCommandManager {
      permissions: [ApplicationCommandPermissionsManager]
    }
  },
  readyTimestamp: 1682779249139,
  event: Collection(0) [Map] {},
  slashCommands: Collection(3) [Map] {
    'ping' => {
      name: 'ping',
      description: 'Ping Dong the bot',
      type: 1,
      options: [],
      userPermissions: [Array],
      botPermissions: [Array],
      run: [AsyncFunction: run]
    },
    'removechannel' => {
      name: 'removechannel',
      description: 'Remove a setted chat channel',
      type: 1,
      options: [Array],
      userPermissions: [Array],
      botPermissions: [Array],
      run: [AsyncFunction: run]
    },
    'setchannel' => {
      name: 'setchannel',
      description: 'Set a channel for the bot to chat with others',
      type: 1,
      options: [Array],
      userPermissions: [Array],
      botPermissions: [Array],
      run: [AsyncFunction: run]
    }
  },
  misc: {
    channels: [ '1101878502996840490', '1064485335976919041' ],
    noMention: false,
    directMessage: true
  },
  [Symbol(kCapture)]: false
}

**Comment by Carbowix** [comment]
It seems to be a general issue with all slash commands of the bot, ill take a look tonight and update as soon as possible.

**Comment by Carbowix** [comment]
So I checked the slash commands and everything seems fine, and the bot was just not connecting properly. The log you provided seems not to be an actual error to be traced.
I need to see your configuration and I need to ask, are you mentioning the bot when you are talking to it or did you open the `noMention` mode, and if you did open it, did you enable the [messageContent](https://github.com/Carbowix/Cleve#how-to-enable-no-mention-feature) intent in your discord developers application portal?

If you need faster help, you can join the [discord](https://discord.com/invite/nntu7rgxtP)
