### ISSUE TITLE
Bot needs the mention before it responds 

### ISSUE THREAD

**Issue by soup-27** [Carbowix/Cleve#59]
Is there a way to make it so you don’t have to mention the bot every time you want to talk to it.

**Comment by Carbowix** [comment]
You can check the [FAQ](https://github.com/Carbowix/Cleve#how-to-enable-no-mention-feature) section to know more about this feature.

**Comment by soup-27** [comment]
How do I use the setchannel command? Just like this or? "@Bot setchannel #channel

**Comment by Carbowix** [comment]
There are no ordinary commands anymore, It utilizes [slashCommands](https://support.discord.com/hc/en-us/articles/1500000368501-Slash-Commands-FAQ#:~:text=WHAT%20ARE%20SLASH%20COMMANDS%3F,to%20use%20your%20favorite%20bot.) completely, so you would do `/setchannel` and it makes you choose your channel and done. 
**Note**: You can set multiple channels for chatting by doing the command multiple times
