### ISSUE TITLE
Invalid Token

### ISSUE THREAD

**Issue by BeingYT143** [Carbowix/Cleve#64]
Hey! Every time I run the bot, I receive the error message "Invalid token provided," even though I have copied and pasted it correctly in the 'config.js' file and the '.env' file. I have renamed the file from '.env.example' to '.env' as required, but the issue persists. I even moved the '.env' file to the 'misc' folder, but I still encounter the same error. Additionally, I have thoroughly verified that the token I'm using is correct.

**Comment by Carbowix** [comment]
You should only choose one way to load your bot token. For the `misc/config.json` way you need to make sure that the token is added to the `"bot_token"` field in it eg. `"bot_token": "OTQ2MTQx..."`
If you'll use the `.env` file instead make sure it's in the **src** folder. Afterward, you should add your token to the file's `BOT_TOKEN` field eg. `BOT_TOKEN=OTQ2MTQx....` or `BOT_TOKEN="OTQ2MTQx..."`
